/**
 * Completion rewards for the 300 quest-report missions.
 *
 * Generated by scripts/generate-mission-completion-rewards.mjs.
 */
import type { ClanTalentChanges, RewardAmountBreakdown } from "../../types/ffta2";

export interface MissionCompletionReward {
    abilityPoints: number;
    abilityPointBreakdown?: readonly RewardAmountBreakdown[];
    clanPoints: number;
    talentChanges?: ClanTalentChanges;
}

export const MISSION_COMPLETION_REWARDS: Readonly<Record<string, MissionCompletionReward>> = {
    "A1-01": {
        "abilityPoints": 80,
        "clanPoints": 2,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "A1-02": {
        "abilityPoints": 30,
        "clanPoints": 16,
        "talentChanges": {
            "aptitude": 1
        }
    },
    "A1-03": {
        "abilityPoints": 30,
        "clanPoints": 6
    },
    "A1-04": {
        "abilityPoints": 30,
        "clanPoints": 32,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "A1-06": {
        "abilityPoints": 80,
        "clanPoints": 4,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "A1-07": {
        "abilityPoints": 30,
        "clanPoints": 12
    },
    "A1-08": {
        "abilityPoints": 30,
        "clanPoints": 16
    },
    "A1-09": {
        "abilityPoints": 30,
        "clanPoints": 66,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "A1-10": {
        "abilityPoints": 30,
        "clanPoints": 24,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "A1-11": {
        "abilityPoints": 80,
        "clanPoints": 6,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 1
        }
    },
    "A1-14": {
        "abilityPoints": 30,
        "clanPoints": 14
    },
    "A1-15": {
        "abilityPoints": 30,
        "clanPoints": 16
    },
    "A1-16": {
        "abilityPoints": 80,
        "clanPoints": 10,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "A2-01": {
        "abilityPoints": 30,
        "clanPoints": 38,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "A2-02": {
        "abilityPoints": 30,
        "clanPoints": 56,
        "talentChanges": {
            "aptitude": 1,
            "teamwork": 1
        }
    },
    "A2-03": {
        "abilityPoints": 30,
        "clanPoints": 36,
        "talentChanges": {
            "aptitude": 1,
            "teamwork": 1
        }
    },
    "A2-04": {
        "abilityPoints": 30,
        "clanPoints": 6
    },
    "A2-05": {
        "abilityPoints": 30,
        "clanPoints": 58,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 1
        }
    },
    "A2-06": {
        "abilityPoints": 30,
        "clanPoints": 84,
        "talentChanges": {
            "aptitude": 2,
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "A2-07": {
        "abilityPoints": 30,
        "clanPoints": 34,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "A2-08": {
        "abilityPoints": 30,
        "clanPoints": 30,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "A2-09": {
        "abilityPoints": 30,
        "clanPoints": 82,
        "talentChanges": {
            "teamwork": 3,
            "adaptability": 2
        }
    },
    "A2-10": {
        "abilityPoints": 30,
        "clanPoints": 78,
        "talentChanges": {
            "aptitude": 2,
            "adaptability": 2
        }
    },
    "A2-11": {
        "abilityPoints": 30,
        "clanPoints": 18
    },
    "A2-12": {
        "abilityPoints": 30,
        "clanPoints": 30,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "A2-13": {
        "abilityPoints": 30,
        "clanPoints": 48,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 1
        }
    },
    "A2-14": {
        "abilityPoints": 30,
        "clanPoints": 36,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "A2-15": {
        "abilityPoints": 30,
        "clanPoints": 26,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "A2-16": {
        "abilityPoints": 30,
        "clanPoints": 34,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "A3-01": {
        "abilityPoints": 30,
        "clanPoints": 52,
        "talentChanges": {
            "teamwork": 3,
            "adaptability": 1
        }
    },
    "A3-03": {
        "abilityPoints": 30,
        "clanPoints": 38,
        "talentChanges": {
            "aptitude": 1,
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "A3-05": {
        "abilityPoints": 30,
        "clanPoints": 68,
        "talentChanges": {
            "teamwork": 3,
            "adaptability": 2
        }
    },
    "A3-06": {
        "abilityPoints": 30,
        "clanPoints": 42,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "A3-08": {
        "abilityPoints": 30,
        "clanPoints": 56,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "A3-09": {
        "abilityPoints": 30,
        "clanPoints": 74,
        "talentChanges": {
            "teamwork": 3,
            "adaptability": 2
        }
    },
    "A3-10": {
        "abilityPoints": 30,
        "clanPoints": 46,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "A3-11": {
        "abilityPoints": 30,
        "clanPoints": 82,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "A3-12": {
        "abilityPoints": 30,
        "clanPoints": 70,
        "talentChanges": {
            "negotiation": 2,
            "adaptability": 2
        }
    },
    "A3-13": {
        "abilityPoints": 30,
        "clanPoints": 82,
        "talentChanges": {
            "teamwork": 4,
            "adaptability": 2
        }
    },
    "A3-14": {
        "abilityPoints": 30,
        "clanPoints": 48,
        "talentChanges": {
            "aptitude": 1,
            "teamwork": 1
        }
    },
    "A3-15": {
        "abilityPoints": 30,
        "clanPoints": 54,
        "talentChanges": {
            "aptitude": 1,
            "adaptability": 1
        }
    },
    "A3-16": {
        "abilityPoints": 30,
        "clanPoints": 92,
        "talentChanges": {
            "negotiation": 3,
            "teamwork": 3,
            "adaptability": 3
        }
    },
    "A4-01": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "teamwork": 5,
            "adaptability": 3
        }
    },
    "A4-02": {
        "abilityPoints": 30,
        "clanPoints": 52,
        "talentChanges": {
            "aptitude": 1,
            "teamwork": 1
        }
    },
    "A4-03": {
        "abilityPoints": 30,
        "clanPoints": 70,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "A4-06": {
        "abilityPoints": 30,
        "clanPoints": 60,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "A4-08": {
        "abilityPoints": 30,
        "clanPoints": 52,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "A4-10": {
        "abilityPoints": 30,
        "clanPoints": 64,
        "talentChanges": {
            "negotiation": 2,
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "A4-11": {
        "abilityPoints": 30,
        "clanPoints": 88,
        "talentChanges": {
            "aptitude": 2,
            "teamwork": 2
        }
    },
    "A4-12": {
        "abilityPoints": 30,
        "clanPoints": 32,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "A4-14": {
        "abilityPoints": 30,
        "clanPoints": 72,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "A4-15": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "teamwork": 3,
            "adaptability": 3
        }
    },
    "A4-16": {
        "abilityPoints": 30,
        "clanPoints": 32,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "A5-01": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "aptitude": 5,
            "teamwork": 5,
            "adaptability": 5
        }
    },
    "A5-03": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "teamwork": 3,
            "adaptability": 3
        }
    },
    "A5-04": {
        "abilityPoints": 30,
        "clanPoints": 36,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "A5-07": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "teamwork": 4,
            "adaptability": 4
        }
    },
    "A5-08": {
        "abilityPoints": 30,
        "clanPoints": 32,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "A5-11": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "teamwork": 4,
            "adaptability": 4
        }
    },
    "A5-14": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "teamwork": 5
        }
    },
    "B1-01": {
        "abilityPoints": 30,
        "clanPoints": 38,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "B1-02": {
        "abilityPoints": 30,
        "clanPoints": 30,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "B1-03": {
        "abilityPoints": 30,
        "clanPoints": 14
    },
    "B1-05": {
        "abilityPoints": 30,
        "clanPoints": 14
    },
    "B1-06": {
        "abilityPoints": 30,
        "clanPoints": 30,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "B1-07": {
        "abilityPoints": 30,
        "clanPoints": 42,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "B1-08": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "B1-09": {
        "abilityPoints": 30,
        "clanPoints": 12
    },
    "B1-10": {
        "abilityPoints": 30,
        "clanPoints": 16
    },
    "B1-11": {
        "abilityPoints": 30,
        "clanPoints": 38,
        "talentChanges": {
            "adaptability": 1
        }
    },
    "B1-12": {
        "abilityPoints": 30,
        "clanPoints": 58,
        "talentChanges": {
            "aptitude": 1
        }
    },
    "B1-14": {
        "abilityPoints": 30,
        "clanPoints": 14
    },
    "B1-15": {
        "abilityPoints": 30,
        "clanPoints": 22,
        "talentChanges": {
            "aptitude": 1,
            "adaptability": 1
        }
    },
    "B1-16": {
        "abilityPoints": 30,
        "clanPoints": 48,
        "talentChanges": {
            "adaptability": 1
        }
    },
    "B2-01": {
        "abilityPoints": 80,
        "clanPoints": 16,
        "talentChanges": {
            "teamwork": 3
        }
    },
    "B2-03": {
        "abilityPoints": 30,
        "clanPoints": 28,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "B2-04": {
        "abilityPoints": 30,
        "clanPoints": 66,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "B2-05": {
        "abilityPoints": 30,
        "clanPoints": 20,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "B2-06": {
        "abilityPoints": 80,
        "clanPoints": 24,
        "talentChanges": {
            "teamwork": 3
        }
    },
    "B2-08": {
        "abilityPoints": 30,
        "clanPoints": 46,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "B2-09": {
        "abilityPoints": 30,
        "clanPoints": 30,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "B2-10": {
        "abilityPoints": 30,
        "clanPoints": 30,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "B2-11": {
        "abilityPoints": 80,
        "clanPoints": 28,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "B2-13": {
        "abilityPoints": 30,
        "clanPoints": 36,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "B2-14": {
        "abilityPoints": 10,
        "clanPoints": 0
    },
    "B2-15": {
        "abilityPoints": 10,
        "clanPoints": 0
    },
    "B2-16": {
        "abilityPoints": 80,
        "clanPoints": 34,
        "talentChanges": {
            "aptitude": 3,
            "adaptability": 4
        }
    },
    "B3-01": {
        "abilityPoints": 30,
        "clanPoints": 46,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "B3-03": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 1
        }
    },
    "B3-04": {
        "abilityPoints": 30,
        "clanPoints": 44,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "B3-06": {
        "abilityPoints": 30,
        "clanPoints": 62,
        "talentChanges": {
            "negotiation": 2,
            "teamwork": 2
        }
    },
    "B3-08": {
        "abilityPoints": 30,
        "clanPoints": 48,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 1
        }
    },
    "B3-09": {
        "abilityPoints": 30,
        "clanPoints": 60,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "B3-11": {
        "abilityPoints": 30,
        "clanPoints": 52,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "B3-13": {
        "abilityPoints": 30,
        "clanPoints": 4
    },
    "B3-14": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "B3-16": {
        "abilityPoints": 30,
        "clanPoints": 12,
        "talentChanges": {
            "adaptability": 1
        }
    },
    "B4-01": {
        "abilityPoints": 30,
        "clanPoints": 14
    },
    "B4-02": {
        "abilityPoints": 30,
        "clanPoints": 60,
        "talentChanges": {
            "negotiation": 2,
            "teamwork": 2
        }
    },
    "B4-03": {
        "abilityPoints": 30,
        "clanPoints": 66,
        "talentChanges": {
            "negotiation": 2,
            "adaptability": 2
        }
    },
    "B4-04": {
        "abilityPoints": 30,
        "clanPoints": 34,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "B4-05": {
        "abilityPoints": 30,
        "clanPoints": 28,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "B4-06": {
        "abilityPoints": 30,
        "clanPoints": 68,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "B4-07": {
        "abilityPoints": 30,
        "clanPoints": 22,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "B4-08": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "B4-09": {
        "abilityPoints": 30,
        "clanPoints": 10
    },
    "B4-10": {
        "abilityPoints": 30,
        "clanPoints": 78,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "B4-11": {
        "abilityPoints": 30,
        "clanPoints": 38,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "B4-12": {
        "abilityPoints": 30,
        "clanPoints": 56,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "B4-13": {
        "abilityPoints": 30,
        "clanPoints": 24,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "B4-14": {
        "abilityPoints": 30,
        "clanPoints": 90,
        "talentChanges": {
            "aptitude": 2
        }
    },
    "B4-15": {
        "abilityPoints": 30,
        "clanPoints": 66,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "B4-16": {
        "abilityPoints": 30,
        "clanPoints": 56,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 1
        }
    },
    "B5-01": {
        "abilityPoints": 30,
        "clanPoints": 26,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "B5-02": {
        "abilityPoints": 30,
        "clanPoints": 80,
        "talentChanges": {
            "negotiation": 2,
            "teamwork": 2
        }
    },
    "B5-03": {
        "abilityPoints": 30,
        "clanPoints": 78,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "B5-04": {
        "abilityPoints": 30,
        "clanPoints": 74,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "B5-05": {
        "abilityPoints": 30,
        "clanPoints": 44,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "B5-06": {
        "abilityPoints": 30,
        "clanPoints": 96,
        "talentChanges": {
            "negotiation": 2,
            "teamwork": 2
        }
    },
    "B5-07": {
        "abilityPoints": 30,
        "clanPoints": 84,
        "talentChanges": {
            "negotiation": 2
        }
    },
    "B5-08": {
        "abilityPoints": 30,
        "clanPoints": 76,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "B5-10": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "aptitude": 3
        }
    },
    "B5-11": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "teamwork": 3
        }
    },
    "B5-14": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "teamwork": 3,
            "adaptability": 3
        }
    },
    "B5-15": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "teamwork": 3
        }
    },
    "B5-16": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "teamwork": 3,
            "adaptability": 3
        }
    },
    "C1-01": {
        "abilityPoints": 30,
        "clanPoints": 80,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "C1-02": {
        "abilityPoints": 30,
        "clanPoints": 78,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "C1-03": {
        "abilityPoints": 30,
        "clanPoints": 86,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "C1-04": {
        "abilityPoints": 30,
        "clanPoints": 38,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 1
        }
    },
    "C1-05": {
        "abilityPoints": 30,
        "clanPoints": 60,
        "talentChanges": {
            "adaptability": 2
        }
    },
    "C1-06": {
        "abilityPoints": 30,
        "clanPoints": 80,
        "talentChanges": {
            "negotiation": 2
        }
    },
    "C1-07": {
        "abilityPoints": 30,
        "clanPoints": 28,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 1
        }
    },
    "C1-09": {
        "abilityPoints": 30,
        "clanPoints": 60,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "C1-10": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "negotiation": 3,
            "teamwork": 3
        }
    },
    "C1-11": {
        "abilityPoints": 30,
        "clanPoints": 18
    },
    "C1-12": {
        "abilityPoints": 30,
        "clanPoints": 24,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "C1-13": {
        "abilityPoints": 30,
        "clanPoints": 42,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "C1-14": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "C1-15": {
        "abilityPoints": 30,
        "clanPoints": 38,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "C1-16": {
        "abilityPoints": 30,
        "clanPoints": 14
    },
    "C2-01": {
        "abilityPoints": 30,
        "clanPoints": 92,
        "talentChanges": {
            "adaptability": 2
        }
    },
    "C2-02": {
        "abilityPoints": 30,
        "clanPoints": 40,
        "talentChanges": {
            "aptitude": 1,
            "adaptability": 1
        }
    },
    "C2-03": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "C2-04": {
        "abilityPoints": 30,
        "clanPoints": 22,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "C2-05": {
        "abilityPoints": 30,
        "clanPoints": 32,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 1
        }
    },
    "C2-06": {
        "abilityPoints": 30,
        "clanPoints": 30,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "C2-07": {
        "abilityPoints": 30,
        "clanPoints": 32,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "C2-08": {
        "abilityPoints": 30,
        "clanPoints": 34,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "C2-09": {
        "abilityPoints": 30,
        "clanPoints": 34,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "C2-10": {
        "abilityPoints": 30,
        "clanPoints": 42,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "C2-11": {
        "abilityPoints": 30,
        "clanPoints": 44,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "C2-12": {
        "abilityPoints": 30,
        "clanPoints": 78,
        "talentChanges": {
            "negotiation": 2,
            "teamwork": 2
        }
    },
    "C2-15": {
        "abilityPoints": 30,
        "clanPoints": 66,
        "talentChanges": {
            "negotiation": 2,
            "teamwork": 2
        }
    },
    "C2-16": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "aptitude": 1,
            "adaptability": 1
        }
    },
    "C3-01": {
        "abilityPoints": 80,
        "clanPoints": 40,
        "talentChanges": {
            "negotiation": 4,
            "teamwork": 3
        }
    },
    "C3-03": {
        "abilityPoints": 30,
        "clanPoints": 44,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "C3-04": {
        "abilityPoints": 30,
        "clanPoints": 32,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "C3-05": {
        "abilityPoints": 30,
        "clanPoints": 72,
        "talentChanges": {
            "negotiation": 2
        }
    },
    "C3-06": {
        "abilityPoints": 80,
        "clanPoints": 42,
        "talentChanges": {
            "aptitude": 3,
            "adaptability": 3
        }
    },
    "C3-08": {
        "abilityPoints": 30,
        "clanPoints": 44,
        "talentChanges": {
            "aptitude": 1,
            "teamwork": 1
        }
    },
    "C3-09": {
        "abilityPoints": 30,
        "clanPoints": 52,
        "talentChanges": {
            "aptitude": 1,
            "adaptability": 1
        }
    },
    "C3-10": {
        "abilityPoints": 30,
        "clanPoints": 80,
        "talentChanges": {
            "negotiation": 2
        }
    },
    "C3-11": {
        "abilityPoints": 80,
        "clanPoints": 44,
        "talentChanges": {
            "aptitude": 3,
            "adaptability": 4
        }
    },
    "C3-13": {
        "abilityPoints": 30,
        "clanPoints": 14
    },
    "C3-14": {
        "abilityPoints": 30,
        "clanPoints": 4
    },
    "C3-15": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "negotiation": 3
        }
    },
    "C3-16": {
        "abilityPoints": 80,
        "clanPoints": 48,
        "talentChanges": {
            "adaptability": 4
        }
    },
    "C4-01": {
        "abilityPoints": 30,
        "clanPoints": 26,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "C4-02": {
        "abilityPoints": 30,
        "clanPoints": 28,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "C4-05": {
        "abilityPoints": 30,
        "clanPoints": 54,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "C4-06": {
        "abilityPoints": 30,
        "clanPoints": 44,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 1,
            "adaptability": 2
        }
    },
    "C4-07": {
        "abilityPoints": 30,
        "clanPoints": 38,
        "talentChanges": {
            "aptitude": 2,
            "adaptability": 1
        }
    },
    "C4-08": {
        "abilityPoints": 30,
        "clanPoints": 48,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "C4-09": {
        "abilityPoints": 30,
        "clanPoints": 36,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "C4-10": {
        "abilityPoints": 30,
        "clanPoints": 46,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "C4-11": {
        "abilityPoints": 30,
        "clanPoints": 60,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "C4-13": {
        "abilityPoints": 30,
        "clanPoints": 58,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "C4-14": {
        "abilityPoints": 30,
        "clanPoints": 56,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "C4-15": {
        "abilityPoints": 30,
        "clanPoints": 12
    },
    "C5-01": {
        "abilityPoints": 30,
        "clanPoints": 72,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "C5-02": {
        "abilityPoints": 30,
        "clanPoints": 70,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "C5-03": {
        "abilityPoints": 30,
        "clanPoints": 94,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "C5-04": {
        "abilityPoints": 30,
        "clanPoints": 80,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "C5-05": {
        "abilityPoints": 30,
        "clanPoints": 88,
        "talentChanges": {
            "aptitude": 2,
            "teamwork": 3,
            "adaptability": 2
        }
    },
    "C5-06": {
        "abilityPoints": 30,
        "clanPoints": 52,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 2,
            "adaptability": 1
        }
    },
    "C5-08": {
        "abilityPoints": 30,
        "clanPoints": 82,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "C5-13": {
        "abilityPoints": 30,
        "clanPoints": 40,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "C5-16": {
        "abilityPoints": 30,
        "clanPoints": 98,
        "talentChanges": {
            "aptitude": 2,
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "D1-01": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 1
        }
    },
    "D1-02": {
        "abilityPoints": 30,
        "clanPoints": 78,
        "talentChanges": {
            "negotiation": 2,
            "aptitude": 2,
            "adaptability": 2
        }
    },
    "D1-05": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "aptitude": 3,
            "teamwork": 3
        }
    },
    "D1-07": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "teamwork": 3,
            "adaptability": 3
        }
    },
    "D1-09": {
        "abilityPoints": 30,
        "clanPoints": 30,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "D1-10": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "teamwork": 3,
            "adaptability": 3
        }
    },
    "D1-13": {
        "abilityPoints": 30,
        "clanPoints": 30,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "D1-14": {
        "abilityPoints": 30,
        "clanPoints": 58,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "D2-01": {
        "abilityPoints": 30,
        "clanPoints": 36,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "D2-02": {
        "abilityPoints": 30,
        "clanPoints": 38,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "D2-03": {
        "abilityPoints": 30,
        "clanPoints": 40,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "D2-04": {
        "abilityPoints": 30,
        "clanPoints": 42,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "D2-05": {
        "abilityPoints": 30,
        "clanPoints": 98,
        "talentChanges": {
            "negotiation": 2,
            "teamwork": 2
        }
    },
    "D2-06": {
        "abilityPoints": 30,
        "clanPoints": 60,
        "talentChanges": {
            "aptitude": 2
        }
    },
    "D2-07": {
        "abilityPoints": 30,
        "clanPoints": 34,
        "talentChanges": {
            "aptitude": 1,
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "D2-08": {
        "abilityPoints": 30,
        "clanPoints": 76,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "D2-09": {
        "abilityPoints": 30,
        "clanPoints": 54,
        "talentChanges": {
            "aptitude": 1,
            "adaptability": 1
        }
    },
    "D2-10": {
        "abilityPoints": 30,
        "clanPoints": 36,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "D2-11": {
        "abilityPoints": 30,
        "clanPoints": 74,
        "talentChanges": {
            "aptitude": 2,
            "teamwork": 2
        }
    },
    "D2-12": {
        "abilityPoints": 30,
        "clanPoints": 34,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "D2-13": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "aptitude": 1,
            "adaptability": 1
        }
    },
    "D2-14": {
        "abilityPoints": 30,
        "clanPoints": 54,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "D2-15": {
        "abilityPoints": 30,
        "clanPoints": 58,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "D2-16": {
        "abilityPoints": 30,
        "clanPoints": 10
    },
    "D3-01": {
        "abilityPoints": 30,
        "clanPoints": 30,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "D3-04": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "D3-05": {
        "abilityPoints": 30,
        "clanPoints": 36,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "D3-06": {
        "abilityPoints": 30,
        "clanPoints": 40,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "D3-07": {
        "abilityPoints": 30,
        "clanPoints": 74,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "D3-09": {
        "abilityPoints": 30,
        "clanPoints": 44,
        "talentChanges": {
            "aptitude": 1,
            "teamwork": 1
        }
    },
    "D3-10": {
        "abilityPoints": 30,
        "clanPoints": 56,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 1
        }
    },
    "D3-11": {
        "abilityPoints": 30,
        "clanPoints": 46,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "D3-12": {
        "abilityPoints": 30,
        "clanPoints": 52,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "D3-15": {
        "abilityPoints": 30,
        "clanPoints": 42,
        "talentChanges": {
            "adaptability": 1
        }
    },
    "D3-16": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "adaptability": 1
        }
    },
    "D4-01": {
        "abilityPoints": 80,
        "clanPoints": 54,
        "talentChanges": {
            "aptitude": 4,
            "adaptability": 5
        }
    },
    "D4-04": {
        "abilityPoints": 30,
        "clanPoints": 82,
        "talentChanges": {
            "aptitude": 2,
            "teamwork": 2
        }
    },
    "D4-06": {
        "abilityPoints": 80,
        "clanPoints": 58,
        "talentChanges": {
            "teamwork": 5
        }
    },
    "D4-07": {
        "abilityPoints": 30,
        "clanPoints": 64,
        "talentChanges": {
            "negotiation": 2,
            "adaptability": 2
        }
    },
    "D4-08": {
        "abilityPoints": 30,
        "clanPoints": 80,
        "talentChanges": {
            "aptitude": 2,
            "adaptability": 2
        }
    },
    "D4-09": {
        "abilityPoints": 30,
        "clanPoints": 38,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "D4-11": {
        "abilityPoints": 80,
        "clanPoints": 64,
        "talentChanges": {
            "negotiation": 4,
            "teamwork": 4
        }
    },
    "D4-12": {
        "abilityPoints": 30,
        "clanPoints": 60,
        "talentChanges": {
            "negotiation": 2
        }
    },
    "D4-14": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "D4-16": {
        "abilityPoints": 80,
        "clanPoints": 68,
        "talentChanges": {
            "teamwork": 5,
            "adaptability": 4
        }
    },
    "D5-01": {
        "abilityPoints": 30,
        "clanPoints": 80,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "D5-02": {
        "abilityPoints": 30,
        "clanPoints": 76,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "D5-03": {
        "abilityPoints": 30,
        "clanPoints": 46,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "D5-05": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 1
        }
    },
    "D5-06": {
        "abilityPoints": 30,
        "clanPoints": 86,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "D5-08": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "D5-12": {
        "abilityPoints": 30,
        "clanPoints": 84,
        "talentChanges": {
            "negotiation": 3
        }
    },
    "D5-13": {
        "abilityPoints": 30,
        "clanPoints": 90,
        "talentChanges": {
            "teamwork": 3,
            "adaptability": 2
        }
    },
    "D5-14": {
        "abilityPoints": 30,
        "clanPoints": 76,
        "talentChanges": {
            "aptitude": 3,
            "adaptability": 2
        }
    },
    "D5-15": {
        "abilityPoints": 30,
        "clanPoints": 72,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "D5-16": {
        "abilityPoints": 30,
        "clanPoints": 62,
        "talentChanges": {
            "adaptability": 2
        }
    },
    "E1-01": {
        "abilityPoints": 30,
        "clanPoints": 44,
        "talentChanges": {
            "aptitude": 2
        }
    },
    "E1-02": {
        "abilityPoints": 30,
        "clanPoints": 36,
        "talentChanges": {
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "E1-03": {
        "abilityPoints": 30,
        "clanPoints": 44,
        "talentChanges": {
            "negotiation": 2,
            "teamwork": 1
        }
    },
    "E1-04": {
        "abilityPoints": 30,
        "clanPoints": 68,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "E1-05": {
        "abilityPoints": 40,
        "abilityPointBreakdown": [
            {
                "amount": 10,
                "label": "Interview"
            },
            {
                "amount": 30,
                "label": "Battle"
            }
        ],
        "clanPoints": 60,
        "talentChanges": {
            "negotiation": 2
        }
    },
    "E1-08": {
        "abilityPoints": 40,
        "abilityPointBreakdown": [
            {
                "amount": 10,
                "label": "Interview"
            },
            {
                "amount": 30,
                "label": "Battle"
            }
        ],
        "clanPoints": 76,
        "talentChanges": {
            "negotiation": 2,
            "adaptability": 2
        }
    },
    "E1-09": {
        "abilityPoints": 30,
        "clanPoints": 30,
        "talentChanges": {
            "aptitude": 1
        }
    },
    "E1-12": {
        "abilityPoints": 40,
        "abilityPointBreakdown": [
            {
                "amount": 10,
                "label": "Interview"
            },
            {
                "amount": 30,
                "label": "Battle"
            }
        ],
        "clanPoints": 86,
        "talentChanges": {
            "negotiation": 2,
            "adaptability": 2
        }
    },
    "E1-13": {
        "abilityPoints": 30,
        "clanPoints": 24,
        "talentChanges": {
            "negotiation": 2,
            "adaptability": 1
        }
    },
    "E1-14": {
        "abilityPoints": 40,
        "abilityPointBreakdown": [
            {
                "amount": 10,
                "label": "Interview"
            },
            {
                "amount": 30,
                "label": "Battle"
            }
        ],
        "clanPoints": 56,
        "talentChanges": {
            "adaptability": 2
        }
    },
    "E1-15": {
        "abilityPoints": 40,
        "abilityPointBreakdown": [
            {
                "amount": 10,
                "label": "Interview"
            },
            {
                "amount": 30,
                "label": "Battle"
            }
        ],
        "clanPoints": 64,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "E1-16": {
        "abilityPoints": 30,
        "clanPoints": 38,
        "talentChanges": {
            "negotiation": 1,
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "E2-05": {
        "abilityPoints": 30,
        "clanPoints": 48,
        "talentChanges": {
            "aptitude": 1,
            "adaptability": 1
        }
    },
    "E2-06": {
        "abilityPoints": 30,
        "clanPoints": 66,
        "talentChanges": {
            "aptitude": 2,
            "adaptability": 2
        }
    },
    "E2-07": {
        "abilityPoints": 30,
        "clanPoints": 84,
        "talentChanges": {
            "aptitude": 2,
            "adaptability": 2
        }
    },
    "E2-08": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "aptitude": 3,
            "teamwork": 3,
            "adaptability": 3
        }
    },
    "E2-09": {
        "abilityPoints": 30,
        "clanPoints": 84,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "E2-10": {
        "abilityPoints": 30,
        "clanPoints": 30,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "E2-11": {
        "abilityPoints": 30,
        "clanPoints": 56,
        "talentChanges": {
            "aptitude": 1
        }
    },
    "E2-12": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "E2-13": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "E2-14": {
        "abilityPoints": 30,
        "clanPoints": 56,
        "talentChanges": {
            "teamwork": 1
        }
    },
    "E2-15": {
        "abilityPoints": 30,
        "clanPoints": 52,
        "talentChanges": {
            "aptitude": 1,
            "teamwork": 1
        }
    },
    "E2-16": {
        "abilityPoints": 30,
        "clanPoints": 82,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "E3-05": {
        "abilityPoints": 30,
        "clanPoints": 40,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "E3-06": {
        "abilityPoints": 30,
        "clanPoints": 60,
        "talentChanges": {
            "aptitude": 2,
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "E3-07": {
        "abilityPoints": 30,
        "clanPoints": 54,
        "talentChanges": {
            "aptitude": 1,
            "teamwork": 1
        }
    },
    "E3-10": {
        "abilityPoints": 30,
        "clanPoints": 36,
        "talentChanges": {
            "negotiation": 1,
            "adaptability": 1
        }
    },
    "E3-11": {
        "abilityPoints": 30,
        "clanPoints": 60,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "E3-12": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "teamwork": 5,
            "adaptability": 5
        }
    },
    "E3-13": {
        "abilityPoints": 30,
        "clanPoints": 58,
        "talentChanges": {
            "adaptability": 1
        }
    },
    "E3-14": {
        "abilityPoints": 30,
        "clanPoints": 66,
        "talentChanges": {
            "adaptability": 2
        }
    },
    "E3-15": {
        "abilityPoints": 30,
        "clanPoints": 74,
        "talentChanges": {
            "adaptability": 2
        }
    },
    "E3-16": {
        "abilityPoints": 30,
        "clanPoints": 92,
        "talentChanges": {
            "adaptability": 2
        }
    },
    "E4-01": {
        "abilityPoints": 30,
        "clanPoints": 84,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "E4-02": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "aptitude": 3,
            "teamwork": 3
        }
    },
    "E4-03": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "teamwork": 3,
            "adaptability": 3
        }
    },
    "E4-04": {
        "abilityPoints": 30,
        "clanPoints": 94,
        "talentChanges": {
            "adaptability": 2
        }
    },
    "E4-05": {
        "abilityPoints": 30,
        "clanPoints": 72,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "E4-06": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "E4-07": {
        "abilityPoints": 30,
        "clanPoints": 90,
        "talentChanges": {
            "teamwork": 2
        }
    },
    "E4-08": {
        "abilityPoints": 30,
        "clanPoints": 58,
        "talentChanges": {
            "aptitude": 1,
            "teamwork": 1,
            "adaptability": 1
        }
    },
    "E4-09": {
        "abilityPoints": 30,
        "clanPoints": 50,
        "talentChanges": {
            "negotiation": 1
        }
    },
    "E4-10": {
        "abilityPoints": 30,
        "clanPoints": 76,
        "talentChanges": {
            "aptitude": 2,
            "teamwork": 2
        }
    },
    "E4-11": {
        "abilityPoints": 30,
        "clanPoints": 62,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "E4-12": {
        "abilityPoints": 30,
        "clanPoints": 96,
        "talentChanges": {
            "negotiation": 2,
            "teamwork": 2
        }
    },
    "E4-14": {
        "abilityPoints": 30,
        "clanPoints": 96,
        "talentChanges": {
            "teamwork": 2,
            "adaptability": 2
        }
    },
    "E4-15": {
        "abilityPoints": 30,
        "clanPoints": 80,
        "talentChanges": {
            "negotiation": 2,
            "teamwork": 2
        }
    },
    "E5-01": {
        "abilityPoints": 80,
        "clanPoints": 74,
        "talentChanges": {
            "aptitude": 5,
            "adaptability": 6
        }
    },
    "E5-06": {
        "abilityPoints": 80,
        "clanPoints": 80,
        "talentChanges": {
            "negotiation": 6,
            "aptitude": 5,
            "teamwork": 6,
            "adaptability": 6
        }
    },
    "E5-08": {
        "abilityPoints": 30,
        "clanPoints": 72,
        "talentChanges": {
            "negotiation": 2,
            "teamwork": 2
        }
    },
    "E5-11": {
        "abilityPoints": 80,
        "clanPoints": 92,
        "talentChanges": {
            "teamwork": 6,
            "adaptability": 7
        }
    },
    "E5-12": {
        "abilityPoints": 30,
        "clanPoints": 98,
        "talentChanges": {
            "negotiation": 3
        }
    },
    "E5-15": {
        "abilityPoints": 30,
        "clanPoints": 99,
        "talentChanges": {
            "negotiation": 3,
            "adaptability": 3
        }
    },
    "E5-16": {
        "abilityPoints": 80,
        "clanPoints": 94,
        "talentChanges": {
            "aptitude": 6,
            "teamwork": 7
        }
    }
};
