/**
 * Validated monster sources for recruit-learnable Blue Magick.
 *
 * Generated by scripts/generate-ability-job-order.mjs.
 */
export interface BlueMagickReference {
    sources: readonly string[];
    note: string | null;
}

export const BLUE_MAGICK_GUIDANCE = [
    "Equip the Learn passive, mastered from the Light Saber, before the monster uses the ability on that unit.",
    "The learner must be affected by the ability and remain eligible to learn it when the action resolves.",
] as const;

export const BLUE_MAGICK_REFERENCE: Readonly<Record<string, BlueMagickReference>> = {
    "magick-hammer": {
        "sources": [
            "Baknamy",
            "Luchorpan"
        ],
        "note": null
    },
    "bad-breath": {
        "sources": [
            "Great Malboro",
            "Malboro",
            "Malboro King"
        ],
        "note": null
    },
    "eerie-sound-wave": {
        "sources": [
            "Great Malboro",
            "Malboro"
        ],
        "note": null
    },
    "dragon-force": {
        "sources": [
            "Fire Drake",
            "Nidhogg"
        ],
        "note": "Use a Beastmaster to make the monster target the learner; enemies do not normally cast this beneficial ability on your clan."
    },
    "expose-weakness": {
        "sources": [
            "Fire Drake",
            "Nagaraja",
            "Thunder Drake",
            "Zahak"
        ],
        "note": null
    },
    "white-wind": {
        "sources": [
            "Sprite"
        ],
        "note": "Use a Beastmaster to make the monster target the learner; enemies do not normally cast this beneficial ability on your clan."
    },
    "mighty-guard": {
        "sources": [
            "Fire Drake",
            "Nagaraja",
            "Zahak"
        ],
        "note": "Use a Beastmaster to make the monster target the learner; enemies do not normally cast this beneficial ability on your clan."
    },
    "night": {
        "sources": [
            "Lamia",
            "Lilith"
        ],
        "note": null
    },
    "quake": {
        "sources": [
            "Headless",
            "Wendigo"
        ],
        "note": null
    },
    "roar": {
        "sources": [
            "Loup-garou",
            "Werewolf",
            "Zaghnal"
        ],
        "note": null
    },
    "sandstorm": {
        "sources": [
            "Antlion",
            "Pit Beast"
        ],
        "note": null
    },
    "screech": {
        "sources": [
            "Hellhound",
            "Wolf",
            "Worgen"
        ],
        "note": null
    },
    "self-destruct": {
        "sources": [
            "Bomb"
        ],
        "note": null
    },
    "unction": {
        "sources": [
            "Red Marshmallow"
        ],
        "note": null
    },
    "war-dance": {
        "sources": [
            "Dreamhare",
            "Hoppy Bunny"
        ],
        "note": "Use a Beastmaster to make the monster target the learner; enemies do not normally cast this beneficial ability on your clan."
    },
    "angel-whisper": {
        "sources": [
            "Sprite"
        ],
        "note": "Use a Beastmaster to make the monster target the learner; enemies do not normally cast this beneficial ability on your clan."
    },
    "cornered": {
        "sources": [
            "Great Tortoise"
        ],
        "note": "Give the learner Reraise first so the KO effect can resolve without ending their participation in the battle."
    },
    "matra-magic": {
        "sources": [
            "Adamantitan"
        ],
        "note": null
    },
    "roulette": {
        "sources": [
            "Ahriman",
            "Plague"
        ],
        "note": "Give the learner Reraise first so the KO effect can resolve without ending their participation in the battle."
    },
    "doom": {
        "sources": [
            "Deathscythe",
            "Oversoul"
        ],
        "note": null
    }
};

export function getBlueMagickReference(abilityId: string): BlueMagickReference | undefined {
    return BLUE_MAGICK_REFERENCE[abilityId === "limit-glove" ? "cornered" : abilityId];
}
